### ISSUE TITLE
Make it possible to use this as a library.

### ISSUE THREAD

**Issue by Yawning** [katzenpost/mailproxy#11]
It occurs to me that this could be used as a library instead of as a daemon by bolting on a different external facing interface to let people send/receive messages.

This will probably save a lot of people, a lot of pain and suffering (#9).

**Comment by david415** [comment]
- send message
- notification when receive queue transitions to non-empty
- possibly expose pop3 session objects for message retreival
- stuff for adding/removing/querying recipients public keys

**Comment by Yawning** [comment]
I'm calling this done now, because people are using this as a library.  Improvements will be tracked under #23.
