### ISSUE TITLE
keyserver requests to unknown recipients return incorrect response

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/mailproxy#37]
When querying the keyserver kaetzchen for an unknown user, the response received is parsed as:
<invaliduser@idefix> (unrecoverable error, keyserver: syntax error)

**Comment by david415** [comment]
What? That's not the response I get when trying to send to a non-existent user. I get this:

```
10:40:15.128 WARN listener/EventSink: ParseKeyQueryResponse returned keyserver: user or public key not found
```
