### ISSUE TITLE
wtf is this auth fail happening for someone's build?

### ISSUE THREAD

**Issue by david415** [katzenpost/mailproxy#39]
18:49:30.395 ERRO provider: Authenticate failed: User: 'vvv', Key: '656F7711B80D59E6734F45FA78C3DDE8121551AD6D190F66D395D2E5AD48DC41'
18:49:30.395 DEBU pki: Incoming: '767676' AD not an IdentityKey?.
18:49:30.395 DEBU incoming:26: Authenticate failed: '767676' (656F7711B80D59E6734F45FA78C3DDE8121551AD6D190F66D395D2E5AD48DC41)
18:49:30.395 ERRO incoming:26: Handshake failed: wire/session: authentication failed
18:49:30.395 DEBU incoming:26: Closing.

**Comment by mixmasala** [comment]
mailproxy was recreating the account directory and keys because it normalized the username although registration_client had not. fixed in https://github.com/katzenpost/registration_client/pull/2
