### ISSUE TITLE
Certificate error when registering a new user

### ISSUE THREAD

**Issue by dsidi** [katzenpost/mailproxy#45]
My group was unable to register a new user to test our script's interaction with Katzenpost. Running

`some_machine:~$ mailproxy -r -account anothercoolguy`

Produces a certificate error:
```
panic: Post https://idefix.katzenpost.mixnetworks.org:39484/registration: x509: certificate has expired or is not yet valid

goroutine 1 [running]:
main.main()
	/home/user/gopath/src/github.com/katzenpost/mailproxy_release/main.go:108 +0xee7
```

**Comment by david415** [comment]
As a project we've mostly abandoned mailproxy and are now working on a better mixnet client that has nothing to do with e-mail protocols.

**Comment by moba** [comment]
This should still be fixed, until there is a replacement testbed. After all, people do want to try it out.

**Comment by david415** [comment]
this should work now... i mean at least registration works ;)
