### ISSUE TITLE
Registration with voting authorities

### ISSUE THREAD

**Issue by cloehle** [katzenpost/mailproxy#50]
The registration doesn't work with voting authorities.
This is fine for now imo, as authority information will probably have to be either hardcoded for each release or supplied with the download. But we could implement the latter one as it would also make testing easier for voting katzenpost.
I would be against supplying the nonvoting authority information as command-line parameters, as the parameter list is already quite long.

Implementing this in [registration_client](https://github.com/katzenpost/registration_client) can be considered so other clients can use it.

**Comment by david415** [comment]
I don't understand the purpose of this ticket. The authorities don't need to keep a database of client link keys. Instead they let anyone query their public database of consensus documents.

**Comment by cloehle** [comment]
Right I should've been more clear, the registration is not concerned with authorities at all except for the mailproxy configuration file generated during the process. Registration now can be done, but the configuration file needs to be modified.
But if #49 is implemented registration will have to deal with authorities.

**Comment by david415** [comment]
What is the connection with authorities? I don't understand what you mean.
